import React, { useState, useEffect } from 'react';
import { Check, Copy, ExternalLink, Plus, X, RefreshCw } from 'lucide-react';
import { useAppContext } from '../AppContext';
import { fetchUserRepos } from '../utils/githubApiUtils';
import { buildMarkdown, GitHubIssuePayload } from '../utils/githubAgentUtils';

const severityEmojis: Record<string, string> = {
  critical: '🔴', high: '🟠', medium: '🟡', low: '🟢'
};

const capitalize = (s: string) => s.charAt(0).toUpperCase() + s.slice(1);

export default function IssueReviewForm() {
  const {
    issuePayload,
    setIssuePayload = () => {},
    githubRepo = '',
    setGithubRepo = () => {},
    githubRepoList = [],
    setGithubRepoList = () => {},
    showComponentHighlights = true,
    setShowComponentHighlights = () => {},
    burnHighlights = true,
    setBurnHighlights = () => {},
    setHighlightedComponents = () => {},
    pushIssueToGitHub = async () => {},
    resetIssue = () => {},
    appendAttribution = true
  } = useAppContext() || {};

  const [reposLoading, setReposLoading] = useState(false);
  const [repoSearch, setRepoSearch] = useState('');
  const [newComponentText, setNewComponentText] = useState('');
  const [newLabelText, setNewLabelText] = useState('');
  const [isCopied, setIsCopied] = useState(false);
  const [isPublishing, setIsPublishing] = useState(false);

  // Load user repositories
  const loadRepos = async () => {
    try {
      const token = await window.snapFrameAPI?.getGitHubToken?.();
      if (token) {
        setReposLoading(true);
        const list = await fetchUserRepos(token);
        setGithubRepoList(list);
        if (list.length > 0 && !githubRepo) {
          setGithubRepo(list[0]);
        }
      }
    } catch (e) {
      console.warn('Failed to load GitHub repos:', e);
    } finally {
      setReposLoading(false);
    }
  };

  useEffect(() => {
    loadRepos();
  }, []);

  if (!issuePayload) return null;

  const handlePublish = async () => {
    setIsPublishing(true);
    try {
      await pushIssueToGitHub();
    } finally {
      setIsPublishing(false);
    }
  };

  const handleCopyMarkdown = async () => {
    try {
      const success = await window.snapFrameAPI?.copyTextToClipboard?.(issuePayload.markdownBody);
      if (!success) throw new Error('Clipboard write returned false');
      setIsCopied(true);
      setTimeout(() => setIsCopied(false), 2000);
    } catch {
      await navigator.clipboard.writeText(issuePayload.markdownBody);
      setIsCopied(true);
      setTimeout(() => setIsCopied(false), 2000);
    }
  };

  const updateField = (updater: (p: GitHubIssuePayload) => GitHubIssuePayload) => {
    const updated = updater(issuePayload);
    const markdownSuffix = appendAttribution 
      ? '\n\n---\n*Generated by [achu](https://achu.design) · Screenshot Agent*' 
      : '';
    updated.markdownBody = buildMarkdown(updated) + markdownSuffix;
    setIssuePayload(updated);
  };

  const updateTitle = (val: string) => updateField(p => ({ ...p, title: val }));
  const updateSeverity = (val: GitHubIssuePayload['severity']) => updateField(p => ({ ...p, severity: val }));
  const updateExpected = (val: string) => updateField(p => ({ ...p, expected: val }));
  const updateActual = (val: string) => updateField(p => ({ ...p, actual: val }));

  const updateStep = (idx: number, val: string) => {
    updateField(p => {
      const steps = [...p.reproSteps];
      steps[idx] = val;
      return { ...p, reproSteps: steps };
    });
  };

  const addStep = () => {
    updateField(p => ({ ...p, reproSteps: [...p.reproSteps, ''] }));
  };

  const removeStep = (idx: number) => {
    updateField(p => ({ ...p, reproSteps: p.reproSteps.filter((_, i) => i !== idx) }));
  };

  const removeComponent = (comp: string) => {
    updateField(p => {
      const filtered = p.components.filter(c => c !== comp);
      setHighlightedComponents(filtered);
      return { ...p, components: filtered };
    });
  };

  const addComponent = (e: React.FormEvent) => {
    e.preventDefault();
    if (!newComponentText.trim()) return;
    const comp = newComponentText.trim();
    if (!issuePayload.components.includes(comp)) {
      updateField(p => {
        const list = [...p.components, comp];
        setHighlightedComponents(list);
        return { ...p, components: list };
      });
    }
    setNewComponentText('');
  };

  const removeLabel = (label: string) => {
    updateField(p => ({ ...p, labels: p.labels.filter(l => l !== label) }));
  };

  const addLabel = (e: React.FormEvent) => {
    e.preventDefault();
    if (!newLabelText.trim()) return;
    const label = newLabelText.trim();
    if (!issuePayload.labels.includes(label)) {
      updateField(p => ({ ...p, labels: [...p.labels, label] }));
    }
    setNewLabelText('');
  };

  const filteredRepos = githubRepoList.filter(r => 
    r.toLowerCase().includes(repoSearch.toLowerCase())
  );

  return (
    <div 
      style={{ 
        display: 'flex', 
        flexDirection: 'column', 
        gap: '0.8rem',
        maxHeight: '450px',
        overflowY: 'auto',
        paddingRight: '4px'
      }}
    >
      {/* Form Title */}
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <span style={{ fontSize: '0.78rem', fontWeight: 600, color: 'var(--text-tertiary)', textTransform: 'uppercase' }}>
          Review Generated Issue
        </span>
        <button 
          className="btn btn-ghost btn-sm" 
          onClick={resetIssue} 
          style={{ padding: '2px 4px', fontSize: '0.7rem' }}
        >
          Reset Form
        </button>
      </div>

      {/* Bug Title */}
      <div className="control-group">
        <span className="control-label">Bug Title</span>
        <input 
          type="text" 
          value={issuePayload.title} 
          onChange={(e) => updateTitle(e.target.value)}
          style={{ width: '100%', marginTop: '3px' }}
        />
      </div>

      {/* Severity Selector */}
      <div className="control-group">
        <span className="control-label">Severity</span>
        <div style={{ display: 'flex', gap: '3px', marginTop: '3px' }}>
          {(['critical', 'high', 'medium', 'low'] as const).map(s => (
            <button
              key={s}
              type="button"
              onClick={() => updateSeverity(s)}
              aria-label={`Set severity to ${capitalize(s)}`}
              style={{
                flex: 1,
                padding: '4px 2px',
                fontSize: '0.68rem',
                fontWeight: 600,
                borderRadius: '3px',
                border: '1px solid var(--border)',
                background: issuePayload.severity === s ? 'var(--surface-3)' : 'var(--surface-2)',
                color: issuePayload.severity === s ? 'var(--text-primary)' : 'var(--text-secondary)',
                boxShadow: issuePayload.severity === s ? '0 0 6px var(--accent)' : 'none',
                cursor: 'pointer'
              }}
            >
              <span aria-hidden="true">{severityEmojis[s]}</span> {capitalize(s)}
            </button>
          ))}
        </div>
      </div>

      {/* Repro Steps */}
      <div className="control-group">
        <span className="control-label">Steps to Reproduce</span>
        <div style={{ display: 'flex', flexDirection: 'column', gap: '4px', marginTop: '4px' }}>
          {issuePayload.reproSteps.map((step, idx) => (
            <div key={idx} style={{ display: 'flex', gap: '4px', alignItems: 'center' }}>
              <span style={{ fontSize: '0.74rem', color: 'var(--text-tertiary)', width: '14px', textAlign: 'right' }}>
                {idx + 1}
              </span>
              <input 
                type="text" 
                value={step} 
                onChange={(e) => updateStep(idx, e.target.value)}
                style={{ flex: 1, padding: '3px 6px', fontSize: '0.76rem' }}
              />
              <button 
                type="button"
                onClick={() => removeStep(idx)}
                style={{ 
                  background: 'none', 
                  border: 'none', 
                  color: '#ef4444', 
                  cursor: 'pointer',
                  padding: '0 4px',
                  fontSize: '0.9rem'
                }}
                title="Remove step"
              >
                ×
              </button>
            </div>
          ))}
          <button 
            type="button"
            onClick={addStep}
            style={{ 
              alignSelf: 'flex-start',
              background: 'none',
              border: 'none',
              color: 'var(--accent)',
              fontSize: '0.74rem',
              cursor: 'pointer',
              display: 'flex',
              alignItems: 'center',
              gap: '2px',
              padding: '2px 4px',
              fontWeight: 600
            }}
          >
            <Plus className="w-3 h-3" /> Add step
          </button>
        </div>
      </div>

      {/* Expected & Actual */}
      <div className="control-group">
        <span className="control-label">Expected Behavior</span>
        <textarea 
          value={issuePayload.expected}
          onChange={(e) => updateExpected(e.target.value)}
          style={{ width: '100%', minHeight: '50px', fontSize: '0.76rem', marginTop: '3px', resize: 'vertical' }}
        />
      </div>

      <div className="control-group">
        <span className="control-label">Actual Behavior</span>
        <textarea 
          value={issuePayload.actual}
          onChange={(e) => updateActual(e.target.value)}
          style={{ width: '100%', minHeight: '50px', fontSize: '0.76rem', marginTop: '3px', resize: 'vertical' }}
        />
      </div>

      {/* Detected UI Components */}
      <div className="control-group">
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
          <span className="control-label">Detected UI Components</span>
          <div style={{ display: 'flex', alignItems: 'center', gap: '4px' }}>
            <input 
              type="checkbox" 
              id="toggle-highlights"
              checked={showComponentHighlights} 
              onChange={(e) => setShowComponentHighlights(e.target.checked)} 
            />
            <label htmlFor="toggle-highlights" style={{ fontSize: '0.7rem', color: 'var(--text-secondary)' }}>Show Canvas Overlay</label>
          </div>
        </div>

        {/* Component Pills */}
        <div style={{ display: 'flex', flexWrap: 'wrap', gap: '4px', marginTop: '4px' }}>
          {issuePayload.components.map(comp => (
            <span 
              key={comp} 
              style={{ 
                display: 'inline-flex', 
                alignItems: 'center', 
                gap: '2px', 
                padding: '2px 6px',
                background: 'rgba(250, 204, 21, 0.12)',
                color: '#facc15',
                border: '1px solid rgba(250, 204, 21, 0.25)',
                borderRadius: '12px',
                fontSize: '0.7rem',
                fontWeight: 500
              }}
            >
              {comp}
              <button 
                type="button"
                onClick={() => removeComponent(comp)}
                style={{ background: 'none', border: 'none', color: '#facc15', cursor: 'pointer', padding: 0, display: 'flex', alignItems: 'center' }}
              >
                <X className="w-2.5 h-2.5" />
              </button>
            </span>
          ))}
        </div>

        <form onSubmit={addComponent} style={{ display: 'flex', gap: '4px', marginTop: '6px' }}>
          <input 
            type="text" 
            placeholder="Add component tag..." 
            value={newComponentText}
            onChange={(e) => setNewComponentText(e.target.value)}
            style={{ flex: 1, padding: '2px 6px', fontSize: '0.74rem' }}
          />
          <button type="submit" className="btn btn-secondary btn-sm" style={{ padding: '0 8px' }}>Add</button>
        </form>
      </div>

      {/* Suggested Labels */}
      <div className="control-group">
        <span className="control-label">GitHub Labels</span>
        <div style={{ display: 'flex', flexWrap: 'wrap', gap: '4px', marginTop: '4px' }}>
          {issuePayload.labels.map(lbl => (
            <span 
              key={lbl} 
              style={{ 
                display: 'inline-flex', 
                alignItems: 'center', 
                gap: '2px', 
                padding: '2px 6px',
                background: 'var(--surface-3)',
                color: 'var(--text-secondary)',
                border: '1px solid var(--border)',
                borderRadius: '12px',
                fontSize: '0.7rem'
              }}
            >
              {lbl}
              <button 
                type="button"
                onClick={() => removeLabel(lbl)}
                style={{ background: 'none', border: 'none', color: 'var(--text-tertiary)', cursor: 'pointer', padding: 0, display: 'flex', alignItems: 'center' }}
              >
                <X className="w-2.5 h-2.5" />
              </button>
            </span>
          ))}
        </div>

        <form onSubmit={addLabel} style={{ display: 'flex', gap: '4px', marginTop: '6px' }}>
          <input 
            type="text" 
            placeholder="Add label..." 
            value={newLabelText}
            onChange={(e) => setNewLabelText(e.target.value)}
            style={{ flex: 1, padding: '2px 6px', fontSize: '0.74rem' }}
          />
          <button type="submit" className="btn btn-secondary btn-sm" style={{ padding: '0 8px' }}>Add</button>
        </form>
      </div>

      <div style={{ borderTop: '1px solid var(--border)', margin: '4px 0' }} />

      {/* Publish & Export Actions */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: '8px' }}>
        <div style={{ display: 'flex', gap: '4px' }}>
          <button 
            type="button"
            className="btn btn-secondary" 
            onClick={handleCopyMarkdown}
            style={{ flex: 1, display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '4px', height: '32px', fontSize: '0.8rem' }}
          >
            {isCopied ? <Check className="w-3.5 h-3.5" style={{ color: '#10b981' }} /> : <Copy className="w-3.5 h-3.5" />}
            {isCopied ? 'Copied!' : 'Copy Markdown'}
          </button>
        </div>

        {/* Repository Search & Selector */}
        <div className="control-group">
          <span className="control-label" style={{ display: 'flex', alignItems: 'center', gap: '4px' }}>
            Publish to Repository
            {reposLoading && <RefreshCw className="w-3 h-3 animate-spin" />}
          </span>

          <input 
            type="text"
            placeholder="Search or enter owner/repo..."
            value={repoSearch || githubRepo}
            onChange={(e) => {
              setRepoSearch(e.target.value);
              setGithubRepo(e.target.value);
            }}
            style={{ width: '100%', marginTop: '3px' }}
          />

          {filteredRepos.length > 0 && repoSearch && repoSearch !== githubRepo && (
            <div 
              style={{ 
                background: 'var(--surface-3)', 
                border: '1px solid var(--border)', 
                borderRadius: '4px',
                maxHeight: '120px',
                overflowY: 'auto',
                marginTop: '2px',
                display: 'flex',
                flexDirection: 'column',
                zIndex: 10
              }}
            >
              {filteredRepos.map(repo => (
                <div 
                  key={repo}
                  onClick={() => {
                    setGithubRepo(repo);
                    setRepoSearch('');
                  }}
                  style={{ 
                    padding: '4px 8px', 
                    fontSize: '0.74rem', 
                    cursor: 'pointer',
                    color: 'var(--text-secondary)',
                    borderBottom: '1px solid var(--border)'
                  }}
                  onMouseEnter={(e) => e.currentTarget.style.background = 'var(--surface-2)'}
                  onMouseLeave={(e) => e.currentTarget.style.background = 'none'}
                >
                  {repo}
                </div>
              ))}
            </div>
          )}
        </div>

        <div 
          style={{ 
            display: 'flex', 
            alignItems: 'center', 
            gap: '6px', 
            fontSize: '0.74rem', 
            color: 'var(--text-secondary)',
            margin: '2px 0' 
          }}
        >
          <input 
            type="checkbox" 
            id="toggle-burn"
            checked={burnHighlights} 
            onChange={(e) => setBurnHighlights(e.target.checked)} 
          />
          <label htmlFor="toggle-burn">Burn highlights into screenshot</label>
        </div>

        {/* Push to GitHub Button */}
        <button 
          type="button"
          className="btn btn-primary"
          onClick={handlePublish}
          disabled={isPublishing || !githubRepo}
          style={{ 
            display: 'flex', 
            alignItems: 'center', 
            justifyContent: 'center', 
            gap: '6px',
            height: '34px',
            fontSize: '0.82rem',
            background: 'linear-gradient(135deg, var(--accent) 0%, #a855f7 100%)'
          }}
        >
          {isPublishing ? (
            <>
              <RefreshCw className="w-4 h-4 animate-spin" /> Publishing...
            </>
          ) : (
            <>
              <ExternalLink className="w-4 h-4" /> Push to GitHub
            </>
          )}
        </button>
      </div>
    </div>
  );
}
