import { describe, it, expect, vi } from 'vitest';
import { safeParseJSON, buildMarkdown, capitalize, generateIssueFromScreenshot } from '../src/renderer/utils/githubAgentUtils';
import { checkOllamaHealth, fetchInstalledModels } from '../src/renderer/utils/ollamaUtils';

describe('GitHub Issue Agent Utils', () => {
  describe('capitalize helper', () => {
    it('should capitalize the first character of a string', () => {
      expect(capitalize('critical')).toBe('Critical');
      expect(capitalize('high')).toBe('High');
      expect(capitalize('')).toBe('');
    });
  });

  describe('safeParseJSON', () => {
    it('should parse a perfectly valid JSON object', () => {
      const valid = '{"title":"Login Bug","severity":"high","expected":"Login to work","actual":"Crash","reproSteps":["Click login","Crash"],"components":["login_btn"],"labels":["bug"]}';
      const parsed = safeParseJSON(valid);
      expect(parsed.title).toBe('Login Bug');
      expect(parsed.severity).toBe('high');
      expect(parsed.expected).toBe('Login to work');
      expect(parsed.actual).toBe('Crash');
      expect(parsed.reproSteps).toEqual(['Click login', 'Crash']);
    });

    it('should parse and repair semi-malformed JSON', () => {
      // Missing closing brace and incomplete commas
      const broken = '{"title": "Unclosed Bug", "severity": "medium", "expected": "Works"';
      const parsed = safeParseJSON(broken);
      expect(parsed.title).toBe('Unclosed Bug');
      expect(parsed.severity).toBe('medium');
      expect(parsed.expected).toBe('Works');
    });

    it('should fallback to regex extraction for completely malformed output', () => {
      const text = 'Here is the bug title: "Regex Fallback Title" and actual: "Regex Fallback Actual" severity is "critical".';
      const parsed = safeParseJSON(text);
      expect(parsed.title).toBe('Regex Fallback Title');
      expect(parsed.actual).toBe('Regex Fallback Actual');
      expect(parsed.severity).toBe('critical');
    });
  });

  describe('buildMarkdown', () => {
    it('should build formatted markdown with severity emojis', () => {
      const payload = {
        title: 'Crash on click',
        severity: 'critical' as const,
        severityReason: 'Auth failure causing crash',
        reproSteps: ['Step one', 'Step two'],
        expected: 'Should authenticate',
        actual: 'Crashed with exception',
        components: ['AuthButton'],
        labels: ['bug'],
        markdownBody: ''
      };
      const markdown = buildMarkdown(payload);
      expect(markdown).toContain('## Bug Report');
      expect(markdown).toContain('🔴 Critical');
      expect(markdown).toContain('Auth failure causing crash');
      expect(markdown).toContain('1. Step one');
      expect(markdown).toContain('2. Step two');
      expect(markdown).toContain('Should authenticate');
      expect(markdown).toContain('Crashed with exception');
      expect(markdown).toContain('`AuthButton`');
    });

    it('should handle empty steps or components gracefully without crashing', () => {
      const payload = {
        title: 'Empty steps bug',
        severity: 'low' as const,
        severityReason: '',
        reproSteps: [],
        expected: '',
        actual: '',
        components: [],
        labels: [],
        markdownBody: ''
      };
      const markdown = buildMarkdown(payload);
      expect(markdown).toContain('🟢 Low');
      expect(markdown).toContain('No steps specified.');
      expect(markdown).toContain('None detected.');
    });

    it('should not contain the watermark by default', () => {
      const payload = {
        title: 'Watermark test',
        severity: 'low' as const,
        severityReason: '',
        reproSteps: [],
        expected: '',
        actual: '',
        components: [],
        labels: [],
        markdownBody: ''
      };
      const markdown = buildMarkdown(payload);
      expect(markdown).not.toContain('*Generated by [achu]');
    });
  });

  describe('checkOllamaHealth', () => {
    it('should return false on fetch exception', async () => {
      vi.stubGlobal('fetch', () => Promise.reject(new Error('Connection refused')));
      const ok = await checkOllamaHealth('http://localhost:11434');
      expect(ok).toBe(false);
      vi.unstubAllGlobals();
    });

    it('should return true on 200 OK response', async () => {
      vi.stubGlobal('fetch', () => Promise.resolve({ ok: true }));
      const ok = await checkOllamaHealth('http://localhost:11434');
      expect(ok).toBe(true);
      vi.unstubAllGlobals();
    });
  });

  describe('fetchInstalledModels', () => {
    it('should filter only vision-capable models', async () => {
      const mockTags = {
        models: [
          { name: 'llama3:8b' },
          { name: 'llava-phi3:latest' },
          { name: 'moondream:latest' },
          { name: 'codegemma:latest' },
          { name: 'llama3.2-vision:latest' },
          { name: 'qwen-vl:latest' },
          { name: 'minicpm-v-vlm:latest' }
        ]
      };
      vi.stubGlobal('fetch', () => Promise.resolve({
        ok: true,
        json: () => Promise.resolve(mockTags)
      }));

      const models = await fetchInstalledModels('http://localhost:11434');
      expect(models.length).toBe(5);
      expect(models).toContain('llava-phi3:latest');
      expect(models).toContain('moondream:latest');
      expect(models).toContain('llama3.2-vision:latest');
      expect(models).toContain('qwen-vl:latest');
      expect(models).toContain('minicpm-v-vlm:latest');
      expect(models).not.toContain('llama3:8b');
      expect(models).not.toContain('codegemma:latest');

      vi.unstubAllGlobals();
    });

    it('returns empty array on fetch failure', async () => {
      vi.stubGlobal('fetch', () => Promise.reject(new Error('network error')));
      const models = await fetchInstalledModels('http://localhost:11434');
      expect(models).toEqual([]);
      vi.unstubAllGlobals();
    });

    it('returns empty array on non-ok response', async () => {
      vi.stubGlobal('fetch', () => Promise.resolve({
        ok: false,
        status: 500,
      }));
      const models = await fetchInstalledModels('http://localhost:11434');
      expect(models).toEqual([]);
      vi.unstubAllGlobals();
    });
  });

  describe('generateIssueFromScreenshot', () => {
    it('generates a payload from valid Ollama JSON response', async () => {
      const ollamaResponse = {
        response: JSON.stringify({
          title: 'Login button crashes app',
          severity: 'critical',
          severityReason: 'App exits completely on tap',
          reproSteps: ['Open app', 'Tap login', 'App closes'],
          expected: 'Login page shows',
          actual: 'App crashes to home screen',
          components: ['LoginButton', 'AuthScreen'],
          labels: ['bug', 'crash'],
        }),
      };

      vi.stubGlobal('fetch', vi.fn().mockResolvedValue({
        ok: true,
        json: () => Promise.resolve(ollamaResponse),
      }));

      const result = await generateIssueFromScreenshot(
        { ocrText: 'Error: crash', ocrWords: [], imageSrc: 'data:image/png;base64,ABC' },
        { endpoint: 'http://localhost:11434', model: 'llava-phi3' }
      );

      expect(result.title).toBe('Login button crashes app');
      expect(result.severity).toBe('critical');
      expect(result.reproSteps).toHaveLength(3);
      expect(result.components).toContain('LoginButton');
      expect(result.labels).toContain('bug');
    });

    it('throws on non-ok Ollama response', async () => {
      vi.stubGlobal('fetch', vi.fn().mockResolvedValue({
        ok: false,
        status: 500,
        statusText: 'Internal Server Error',
      }));

      await expect(
        generateIssueFromScreenshot(
          { ocrText: '', ocrWords: [], imageSrc: 'data:image/png;base64,ABC' },
          { endpoint: 'http://localhost:11434', model: 'llava-phi3' }
        )
      ).rejects.toThrow('Ollama response not OK: 500');
    });

    it('falls back to safeParseJSON when response is malformed', async () => {
      const ollamaResponse = {
        response: 'Here is the bug title: "Fallback Title" and actual: "It broke" severity: "high".',
      };

      vi.stubGlobal('fetch', vi.fn().mockResolvedValue({
        ok: true,
        json: () => Promise.resolve(ollamaResponse),
      }));

      const result = await generateIssueFromScreenshot(
        { ocrText: '', ocrWords: [], imageSrc: 'data:img,XYZ' },
        { endpoint: 'http://localhost:11434', model: 'llava-phi3' }
      );

      expect(result.title).toBe('Fallback Title');
      expect(result.severity).toBe('high');
      expect(result.actual).toBe('It broke');
    });

    it('strips data URL prefix from imageSrc before sending', async () => {
      let capturedImages: string[] = [];
      vi.stubGlobal('fetch', vi.fn().mockImplementation(async (_url: string, opts: any) => {
        capturedImages = JSON.parse(opts.body).images;
        return {
          ok: true,
          json: () => Promise.resolve({ response: '{"title":"T","severity":"low"}' }),
        };
      }));

      await generateIssueFromScreenshot(
        { ocrText: '', ocrWords: [], imageSrc: 'data:image/png;base64,REAL_BASE64' },
        { endpoint: 'http://localhost:11434', model: 'llava-phi3' }
      );

      expect(capturedImages[0]).not.toContain('data:');
      expect(capturedImages[0]).not.toContain(',');
      expect(capturedImages[0]).toBe('REAL_BASE64');
    });

    it('handles empty response string gracefully', async () => {
      vi.stubGlobal('fetch', vi.fn().mockResolvedValue({
        ok: true,
        json: () => Promise.resolve({ response: '' }),
      }));

      const result = await generateIssueFromScreenshot(
        { ocrText: '', ocrWords: [], imageSrc: 'data:img,X' },
        { endpoint: 'http://localhost:11434', model: 'llava-phi3' }
      );

      // Fallback produces safe defaults
      expect(result.title).toBe('Untitled Bug');
      expect(result.severity).toBe('medium');
      expect(result.reproSteps).toEqual([]);
      expect(result.labels).toEqual(['bug']);
    });
  });
});
