import type { RenderConfig, Annotation, RedactionItem } from '../canvasRenderer';
import type { CompressionMode } from '../hooks/useExport';
import type { VibePalette } from '../utils/colorExtractor';
import type { ShaderType, ShaderParams } from '../shaders/shaderPresets';
import type { WordBoundingBox, GitHubIssuePayload } from '../utils/githubAgentUtils';
import type { GalleryItem } from '../hooks/useGallery';

export interface AppContextType {
  // Config state
  padding: number; setPadding: React.Dispatch<React.SetStateAction<number>>;
  rounded: number; setRounded: React.Dispatch<React.SetStateAction<number>>;
  shadow: number; setShadow: React.Dispatch<React.SetStateAction<number>>;
  shadowColor: string; setShadowColor: React.Dispatch<React.SetStateAction<string>>;
  shadowEnabled: boolean; setShadowEnabled: React.Dispatch<React.SetStateAction<boolean>>;
  inset: number; setInset: React.Dispatch<React.SetStateAction<number>>;
  insetColor: string; setInsetColor: React.Dispatch<React.SetStateAction<string>>;
  border: number; setBorder: React.Dispatch<React.SetStateAction<number>>;
  borderColor: string; setBorderColor: React.Dispatch<React.SetStateAction<string>>;
  scale: number; setScale: React.Dispatch<React.SetStateAction<number>>;
  backgroundType: 'gradient' | 'color' | 'blur' | 'mesh' | 'shader'; setBackgroundType: React.Dispatch<React.SetStateAction<'gradient' | 'color' | 'blur' | 'mesh' | 'shader'>>;
  backgroundValue: string; setBackgroundValue: React.Dispatch<React.SetStateAction<string>>;
  bgGrain: number; setBgGrain: React.Dispatch<React.SetStateAction<number>>;
  lightRaysStyle: 'none' | 'diagonal' | 'spotlight' | 'aurora'; setLightRaysStyle: React.Dispatch<React.SetStateAction<'none' | 'diagonal' | 'spotlight' | 'aurora'>>;
  lightRaysOpacity: number; setLightRaysOpacity: React.Dispatch<React.SetStateAction<number>>;
  lightRaysAngle: number; setLightRaysAngle: React.Dispatch<React.SetStateAction<number>>;
  lightRaysCount: number; setLightRaysCount: React.Dispatch<React.SetStateAction<number>>;
  lightRaysSourceX: number; setLightRaysSourceX: React.Dispatch<React.SetStateAction<number>>;
  lightRaysSourceY: number; setLightRaysSourceY: React.Dispatch<React.SetStateAction<number>>;
  aspectRatio: string; setAspectRatio: React.Dispatch<React.SetStateAction<string>>;
  canvasWidth: number; setCanvasWidth: React.Dispatch<React.SetStateAction<number>>;
  canvasHeight: number; setCanvasHeight: React.Dispatch<React.SetStateAction<number>>;
  selectedPreset: string; setSelectedPreset: React.Dispatch<React.SetStateAction<string>>;
  showSafeZone: boolean; setShowSafeZone: React.Dispatch<React.SetStateAction<boolean>>;
  paddingMode: 'fit' | 'fill'; setPaddingMode: React.Dispatch<React.SetStateAction<'fit' | 'fill'>>;
  chromeStyle: 'mac' | 'windows' | 'none'; setChromeStyle: React.Dispatch<React.SetStateAction<'mac' | 'windows' | 'none'>>;
  chromeTheme: 'dark' | 'light'; setChromeTheme: React.Dispatch<React.SetStateAction<'dark' | 'light'>>;
  blurDensity: number; setBlurDensity: React.Dispatch<React.SetStateAction<number>>;
  noImageMode: boolean; setNoImageMode: React.Dispatch<React.SetStateAction<boolean>>;
  meshPoints: Array<{ id: string; color: string; x: number; y: number; radius: number }>; setMeshPoints: React.Dispatch<React.SetStateAction<Array<{ id: string; color: string; x: number; y: number; radius: number }>>>;
  meshBlur: number; setMeshBlur: React.Dispatch<React.SetStateAction<number>>;
  meshGrain: number; setMeshGrain: React.Dispatch<React.SetStateAction<number>>;
  meshOpacity: number; setMeshOpacity: React.Dispatch<React.SetStateAction<number>>;
  meshSpread: number; setMeshSpread: React.Dispatch<React.SetStateAction<number>>;
  meshDataUrl: string; setMeshDataUrl: React.Dispatch<React.SetStateAction<string>>;
  activePointIdx: number; setActivePointIdx: React.Dispatch<React.SetStateAction<number>>;
  shaderType: ShaderType; setShaderType: React.Dispatch<React.SetStateAction<ShaderType>>;
  shaderColors: string[]; setShaderColors: React.Dispatch<React.SetStateAction<string[]>>;
  shaderParams: ShaderParams; setShaderParams: React.Dispatch<React.SetStateAction<ShaderParams>>;
  shaderDataUrl: string; setShaderDataUrl: React.Dispatch<React.SetStateAction<string>>;
  watermarkEnabled: boolean; setWatermarkEnabled: React.Dispatch<React.SetStateAction<boolean>>;
  watermarkText: string; setWatermarkText: React.Dispatch<React.SetStateAction<string>>;
  watermarkSize: number; setWatermarkSize: React.Dispatch<React.SetStateAction<number>>;
  watermarkPosition: 'left' | 'middle' | 'right' | 'top left' | 'top middle' | 'top right'; setWatermarkPosition: React.Dispatch<React.SetStateAction<'left' | 'middle' | 'right' | 'top left' | 'top middle' | 'top right'>>;
  watermarkOpacity: number; setWatermarkOpacity: React.Dispatch<React.SetStateAction<number>>;
  watermarkFont: string; setWatermarkFont: React.Dispatch<React.SetStateAction<string>>;
  watermarkBold: boolean; setWatermarkBold: React.Dispatch<React.SetStateAction<boolean>>;
  watermarkItalic: boolean; setWatermarkItalic: React.Dispatch<React.SetStateAction<boolean>>;
  annotationFont: string; setAnnotationFont: React.Dispatch<React.SetStateAction<string>>;
  annotationFontSize: number; setAnnotationFontSize: React.Dispatch<React.SetStateAction<number>>;
  annotationBold: boolean; setAnnotationBold: React.Dispatch<React.SetStateAction<boolean>>;
  annotationItalic: boolean; setAnnotationItalic: React.Dispatch<React.SetStateAction<boolean>>;
  annotationOutlineEnabled: boolean; setAnnotationOutlineEnabled: React.Dispatch<React.SetStateAction<boolean>>;
  annotationOutlineColor: string; setAnnotationOutlineColor: React.Dispatch<React.SetStateAction<string>>;
  annotationOutlineWidth: number; setAnnotationOutlineWidth: React.Dispatch<React.SetStateAction<number>>;
  annotationGradientEnabled: boolean; setAnnotationGradientEnabled: React.Dispatch<React.SetStateAction<boolean>>;
  annotationGradientColor1: string; setAnnotationGradientColor1: React.Dispatch<React.SetStateAction<string>>;
  annotationGradientColor2: string; setAnnotationGradientColor2: React.Dispatch<React.SetStateAction<string>>;
  annotationGradientAngle: number; setAnnotationGradientAngle: React.Dispatch<React.SetStateAction<number>>;
  systemFonts: string[]; setSystemFonts: React.Dispatch<React.SetStateAction<string[]>>;
  previewFont: string | null; setPreviewFont: React.Dispatch<React.SetStateAction<string | null>>;
  position: string; setPosition: React.Dispatch<React.SetStateAction<string>>;
  activeTool: 'pointer' | 'rect' | 'filled-rect' | 'circle' | 'filled-circle' | 'line' | 'arrow' | 'text' | 'pen' | 'emoji'; setActiveTool: React.Dispatch<React.SetStateAction<'pointer' | 'rect' | 'filled-rect' | 'circle' | 'filled-circle' | 'line' | 'arrow' | 'text' | 'pen' | 'emoji'>>;
  arrowStyle: 'classic' | 'dashed' | 'tapered' | 'curved'; setArrowStyle: React.Dispatch<React.SetStateAction<'classic' | 'dashed' | 'tapered' | 'curved'>>;
  annotations: Annotation[]; setAnnotations: React.Dispatch<React.SetStateAction<Annotation[]>>;
  annotationColor: string; setAnnotationColor: React.Dispatch<React.SetStateAction<string>>;
  annotationStrokeWidth: number; setAnnotationStrokeWidth: React.Dispatch<React.SetStateAction<number>>;
  annotationDisplayWidth: number; setAnnotationDisplayWidth: React.Dispatch<React.SetStateAction<number>>;
  redactions: RedactionItem[]; setRedactions: React.Dispatch<React.SetStateAction<RedactionItem[]>>;
  isScanningSecrets: boolean; setIsScanningSecrets: React.Dispatch<React.SetStateAction<boolean>>;
  scanProgress: number; setScanProgress: React.Dispatch<React.SetStateAction<number>>;
  hoveredRedactionId: string | null; setHoveredRedactionId: React.Dispatch<React.SetStateAction<string | null>>;
  redactionStyle: 'blur' | 'solid'; setRedactionStyle: React.Dispatch<React.SetStateAction<'blur' | 'solid'>>;
  promptConfig: { message: string; defaultValue: string; resolve: (val: string | null) => void } | null; setPromptConfig: React.Dispatch<React.SetStateAction<{ message: string; defaultValue: string; resolve: (val: string | null) => void } | null>>;
  sidebarVisible: boolean; setSidebarVisible: React.Dispatch<React.SetStateAction<boolean>>;
  secondarySidebarVisible: boolean; setSecondarySidebarVisible: React.Dispatch<React.SetStateAction<boolean>>;
  secondarySidebarPosition: 'left' | 'right'; setSecondarySidebarPosition: React.Dispatch<React.SetStateAction<'left' | 'right'>>;
  settingsVisible: boolean; setSettingsVisible: React.Dispatch<React.SetStateAction<boolean>>;
  helpVisible: boolean; setHelpVisible: React.Dispatch<React.SetStateAction<boolean>>;
  updateAvailable: { version: string; releaseUrl: string } | null; setUpdateAvailable: React.Dispatch<React.SetStateAction<{ version: string; releaseUrl: string } | null>>;
  imageSrc: string | null; setImageSrc: React.Dispatch<React.SetStateAction<string | null>>;
  documentName: string | null; setDocumentName: React.Dispatch<React.SetStateAction<string | null>>;
  isDragging: boolean; setIsDragging: React.Dispatch<React.SetStateAction<boolean>>;
  customPresets: any[]; setCustomPresets: React.Dispatch<React.SetStateAction<any[]>>;
  newPresetName: string; setNewPresetName: React.Dispatch<React.SetStateAction<string>>;
  showAdvancedInset: boolean; setShowAdvancedInset: React.Dispatch<React.SetStateAction<boolean>>;
  showAdvancedShadow: boolean; setShowAdvancedShadow: React.Dispatch<React.SetStateAction<boolean>>;
  showAdvancedBorder: boolean; setShowAdvancedBorder: React.Dispatch<React.SetStateAction<boolean>>;
  exportFormat: 'png' | 'jpeg' | 'webp'; setExportFormat: React.Dispatch<React.SetStateAction<'png' | 'jpeg' | 'webp'>>;
  jpegQuality: number; setJpegQuality: React.Dispatch<React.SetStateAction<number>>;
  compressionMode: CompressionMode; setCompressionMode: React.Dispatch<React.SetStateAction<CompressionMode>>;
  autoImportCaptured: boolean; setAutoImportCaptured: (val: boolean) => void;
  checkForUpdatesOnStartup: boolean; setCheckForUpdatesOnStartup: (val: boolean) => void;
  captureShortcut: string; setCaptureShortcut: (val: string) => void;
  zoomLevel: string; setZoomLevel: React.Dispatch<React.SetStateAction<string>>;
  history: any[]; setHistory: React.Dispatch<React.SetStateAction<any[]>>;
  historyIndex: number; setHistoryIndex: React.Dispatch<React.SetStateAction<number>>;
  showHollywoodPalettes: boolean; setShowHollywoodPalettes: React.Dispatch<React.SetStateAction<boolean>>;
  selectedGradientCategory: 'classic' | 'os' | 'disney' | 'marvel' | 'hollywood'; setSelectedGradientCategory: React.Dispatch<React.SetStateAction<'classic' | 'os' | 'disney' | 'marvel' | 'hollywood'>>;
  showHollywoodMeshPalettes: boolean; setShowHollywoodMeshPalettes: React.Dispatch<React.SetStateAction<boolean>>;
  appTheme: 'dark' | 'light'; setAppTheme: React.Dispatch<React.SetStateAction<'dark' | 'light'>>;
  sidebarPosition: 'left' | 'right'; setSidebarPosition: React.Dispatch<React.SetStateAction<'left' | 'right'>>;
  vibePalette: VibePalette | null;
  vibeVariantIndex: number;
  vibeUpdateDrawColor: boolean; setVibeUpdateDrawColor: React.Dispatch<React.SetStateAction<boolean>>;
  applyAutoVibe: () => Promise<void>;

  // Code Studio
  codeStudioActive: boolean; setCodeStudioActive: React.Dispatch<React.SetStateAction<boolean>>;
  codeStudioCode: string; setCodeStudioCode: React.Dispatch<React.SetStateAction<string>>;
  codeStudioLanguage: string; setCodeStudioLanguage: React.Dispatch<React.SetStateAction<string>>;
  codeStudioTheme: string; setCodeStudioTheme: React.Dispatch<React.SetStateAction<string>>;
  codeStudioFontSize: number; setCodeStudioFontSize: React.Dispatch<React.SetStateAction<number>>;
  codeStudioLineNumbers: boolean; setCodeStudioLineNumbers: React.Dispatch<React.SetStateAction<boolean>>;
  codeStudioShowLanguage: boolean; setCodeStudioShowLanguage: React.Dispatch<React.SetStateAction<boolean>>;
  codeStudioBreakpoints: number[]; setCodeStudioBreakpoints: React.Dispatch<React.SetStateAction<number[]>>;
  codeStudioShowBreakpoints: boolean; setCodeStudioShowBreakpoints: React.Dispatch<React.SetStateAction<boolean>>;
  toggleCodeStudio: (active: boolean, codeText?: string, codeLang?: string) => void;
  screenshotBgConfig: any; setScreenshotBgConfig: React.Dispatch<React.SetStateAction<any>>;
  codeStudioBgConfig: any; setCodeStudioBgConfig: React.Dispatch<React.SetStateAction<any>>;


  // Refs
  fileInputRef: React.RefObject<HTMLInputElement | null>;
  colorInputRef: React.RefObject<HTMLInputElement | null>;

  // Functions
  getCurrentConfig: () => RenderConfig;
  pushHistory: (config: any) => void;
  applyConfig: (config: RenderConfig) => void;
  handleUndo: () => void;
  handleRedo: () => void;
  selectFile: () => Promise<void>;
  handleHTMLFileInput: (e: React.ChangeEvent<HTMLInputElement>) => void;
  pasteFromClipboard: () => Promise<void>;
  saveCustomPreset: () => void;
  deleteCustomPreset: (id: string, e: React.MouseEvent) => void;
  copyBeautifiedImage: (caption?: string) => Promise<void>;
  triggerExport: () => void;
  exportBeforeAfter: () => void;
  copyBeforeAfter: () => Promise<void>;
  saveToGallery: () => Promise<{ success: boolean; path?: string; name?: string; error?: { code: string; message: string } }>;
  handleSaveToGallery: () => Promise<void>;
  galleryToast: string | null;
  showToast: (message: string, duration?: number) => void;
  shareAchuPromptOpen: boolean;
  setShareAchuPromptOpen: React.Dispatch<React.SetStateAction<boolean>>;
  selectBackgroundPreset: (preset: any) => void;
  handleSliderRelease: () => void;
  getZoomStyle: () => React.CSSProperties;
  applyMeshPalette: (colors: string[]) => void;
  generateRandomPalette: () => void;
  handleDragOver: (e: React.DragEvent) => void;
  handleDragLeave: (e: React.DragEvent) => void;
  handleDrop: (e: React.DragEvent) => void;
  customPrompt: (message: string, defaultValue?: string) => Promise<string | null>;
  handlePointerDown: (e: React.PointerEvent, idx: number) => void;
  handlePointerMove: (e: React.PointerEvent) => void;
  handlePointerUp: (e: React.PointerEvent) => void;
  scanForSecrets: () => Promise<void>;
  toggleRedaction: (id: string) => void;
  redactAll: () => void;
  revealAll: () => void;
  resetStyles: () => void;
  clearWorkspace: () => void;
  openGalleryImage: (item: GalleryItem) => Promise<{ success: boolean; error?: { code: string; message: string } }>;

  // Issue Agent states & config
  issuePayload: GitHubIssuePayload | null; setIssuePayload: React.Dispatch<React.SetStateAction<GitHubIssuePayload | null>>;
  isGeneratingIssue: boolean; setIsGeneratingIssue: React.Dispatch<React.SetStateAction<boolean>>;
  issueError: string | null; setIssueError: React.Dispatch<React.SetStateAction<string | null>>;
  aiProvider: 'ollama' | 'openai' | 'google' | 'claude'; setAiProvider: (provider: 'ollama' | 'openai' | 'google' | 'claude') => void;
  ollamaEndpoint: string; setOllamaEndpoint: (endpoint: string) => void;
  ollamaModel: string; setOllamaModel: (model: string) => void;
  openaiModel: string; setOpenaiModel: (model: string) => void;
  googleModel: string; setGoogleModel: (model: string) => void;
  claudeModel: string; setClaudeModel: (model: string) => void;
  openaiModelsList: { value: string; label: string }[];
  googleModelsList: { value: string; label: string }[];
  claudeModelsList: { value: string; label: string }[];
  ollamaAvailable: boolean; setOllamaAvailable: React.Dispatch<React.SetStateAction<boolean>>;
  githubRepo: string; setGithubRepo: (repo: string) => void;
  githubRepoList: string[]; setGithubRepoList: React.Dispatch<React.SetStateAction<string[]>>;
  showComponentHighlights: boolean; setShowComponentHighlights: (show: boolean) => void;
  burnHighlights: boolean; setBurnHighlights: (burn: boolean) => void;
  appendAttribution: boolean; setAppendAttribution: (append: boolean) => void;
  cachedOcrResult: { text: string; words: WordBoundingBox[] } | null; setCachedOcrResult: React.Dispatch<React.SetStateAction<{ text: string; words: WordBoundingBox[] } | null>>;
  highlightedComponents: string[]; setHighlightedComponents: React.Dispatch<React.SetStateAction<string[]>>;
  localFallbackAvailable: boolean; setLocalFallbackAvailable: React.Dispatch<React.SetStateAction<boolean>>;
  userInstruction: string; setUserInstruction: React.Dispatch<React.SetStateAction<string>>;

  // Issue Agent actions
  generateIssue: () => Promise<void>;
  generateIssueOffline: () => void;
  pushIssueToGitHub: () => Promise<void>;
  resetIssue: () => void;
  exportBeautifiedScreenshot: (burnHighlights?: boolean) => Promise<string>;
  triggerAiHealthCheck: () => void;
}
